---
title: "EDS212_Day2_Part2"
output: html_document
date: "2022-08-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library("palmerpenguins")
```

```{r}
head(penguins)
glimpse(penguins)
tail(penguins)
```

### Scatterplot of body mass versus flipper length

1.  We need to tell it that we are using ggplot.
2.  We need to tell it about the data including the name of the dataframe and what variables we have.
3.  Tell it about the geometry and the type of graph we want.

```{r}
ggplot(data=penguins, aes(x = body_mass_g, y = flipper_length_mm)) + 
  geom_point(aes(color = species), size = 1) +
  facet_wrap(~island) +
  theme_minimal() + 
  labs(x = "Body mass (g)",
       y = "Flipper length (mm)",
       title = "Palmer penguin size measurements")
```

### Create a ggplot graph of penguin bill length versus bill depth with point color dependent on species

```{r}
ggplot(data=penguins, aes(x = bill_length_mm, y = bill_depth_mm)) + 
  geom_point(aes(color=species), size = 1) +
  labs(x = "Bill length (mm)",
       y = "Bill depth (mm)",
       title = "Palmer penguin bill measurements")
```

```{r}
ggplot(data=penguins, aes(x = species, y = flipper_length_mm)) + 
  geom_jitter(aes(color=species), size = 1, width = 0.4) + 
  labs(x = "Species",
       y = "Flipper length (mm)",
       title = "Palmer penguin flipper length by species")
```


